# Generated by Django 4.1.7 on 2023-03-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_sidemenucontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidemenucontent',
            name='svg',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
